name: matrix in githubactions
on:
 push:
  branches:
   - master
jobs:
 build-job:
  strategy:
   matrix:
    node-version: [12,14,16]
    operating-system: [ubuntu-latest, windows-latest]
  runs-on: ${{operating-system}}
  steps:
   - name: Clone the code 
     uses: actions/checkout@v3
   - name: Install nodeJS 
     uses: actions/setup-node@v3
     with:
      node-version: ${{node-version}}
   - name: Install dependencies 
     run: npm ci
   - name: Build the code 
     run: npm run build
